# Generated by Django 4.1.1 on 2022-10-05 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_alter_users_phone'),
        ('buildings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buildingaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.users'),
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
